routes/__init__.py
from flask_security import login_required, roles_required
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask import abort, jsonify
from main import User, Role, get_user_datastore, db, Usage
from forms import UpdateUserDataForm, AddNewRoleForm
from flask_login import current_user

route_blueprint = Blueprint('recipes',__name__)

# Views

import sys

@route_blueprint.route('/')
@login_required
def home():
    return render_template('index.html', title="Welcome", user=current_user)

@route_blueprint.route('/admin')
@roles_required('admin')
def admin():
    return render_template('admin.html', title="Admin Area")

@route_blueprint.route('/admin/users')
@roles_required('admin')
def users():
    return render_template('users.html', users=User.query.all(), title="Users")

@route_blueprint.route('/admin/modify_user', methods=['GET', 'POST'])
@roles_required('admin')
def modify_user():
    arg_email = request.args.get('email')
    user = get_user_datastore().find_user(email=arg_email)
    if not user:
        flash("Invalid User %s" % arg_email)
        return redirect(url_for('recipes.users'))
    form = UpdateUserDataForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user.email = form.email.data
                if form.rfid_tag.data:
                    user.rfid_tag = form.rfid_tag.data
                else:
                    user.rfid_tag = None
              #  user.active = form.active.data
              #  user.confirmed = form.confirmed.data
                user.name = form.name.data
                user.street = form.street.data
                user.city = form.city.data
                db.session.commit()

                flash("Updated user %s" % form.rfid_tag.data)
            except:
                flash("Error setting new data for %s" % user.email)
            return redirect(url_for('recipes.users'))
        else:
            app.logger.debug(form.errors)
            flash("Error updating for %s:%s" % ( user.email, form.errors) )
            return redirect(url_for('recipes.users'))
    else:
        return render_template('modify_user.html', title="Modify User", user=user, form=form)

@route_blueprint.route('/admin/roles',methods=['GET', 'POST'])
@roles_required('admin')
def roles():
    form = AddNewRoleForm()
    if request.method == "POST":
        if form.validate_on_submit():
            try:
                role_name = form.role.data
                assert not Role.query.filter_by(name=role_name).first(), "role already exists"
                get_user_datastore().find_or_create_role(role_name)
                db.session.commit()

                flash("Created role %s" % role_name)
            except Exception as e:
                flash("Error creation new role %s: %s" % (role_name, str(e) ))
    return render_template('roles.html', title="Roles", form=form, User=User, Role=Role)

@route_blueprint.route('/admin/role-delete')
@roles_required('admin')
def role_delete():
    arg_role_name = request.args.get('role')
    role = get_user_datastore().find_role(arg_role_name)
    if not role:
        flash("Invalid role: %s" % arg_role_name)
    if request.method == 'GET':
        arg_confirm = request.args.get('confirmed')
        if not arg_confirm: 
            return render_template('confirm.html',
                                   title='Delete role',
                                   message=('Delete role "%s"' % role.name),
                                   url_yes=url_for('recipes.role_delete',
                                       role=arg_role_name,
                                       confirmed='yes'),
                                   url_no=url_for('recipes.roles'))
        elif arg_confirm == 'yes':
            db.session.delete(role)
            db.session.commit()
            flash("Role %s deleted" % arg_role_name)
        else:
            flash("Invalid confirm arg: %s" % arg_confirm)
    elif request.method == "POST":
        if form.validate_on_submit():
            try:
                role_name = form.role.name
                assert not Role.query.filter_by(name=role_name).first(), "role already exists"
                get_user_datastore().find_or_create_role(role_name)
                db.session.commit()

                flash("Created role %s" % role_name)
            except Exception as e:
                flash("Error creation new role %s" % (role_name, str(e) ))
        
    return redirect(url_for('recipes.roles'))

@route_blueprint.route('/admin/role-user-add')
@roles_required('admin')
def role_add_user():
    arg_role_name = request.args.get('role')
    arg_user_mail = request.args.get('user')
  
    if not arg_role_name or not arg_user_mail:
        flash("no role or user arg")
        return redirect(url_for("recipes.roles"))
        
    role = get_user_datastore().find_role(arg_role_name)
    user = get_user_datastore().get_user(arg_user_mail)

    if not role or not user:
        flash("Invalid role or user")
        return redirect(url_for("recipes.roles"))

    if user.has_role(role):
        flash("User aleady has role")
        return redirect(url_for("recipes.roles"))

    get_user_datastore().add_role_to_user(user, role.name)
    db.session.commit()
    flash("added user(%s) to role(%s)" %(user.email, role.name))
    return redirect(url_for("recipes.roles"))


@route_blueprint.route('/admin/role-user-rm')
@roles_required('admin')
def role_rm_user():
    arg_role_name = request.args.get('role')
    arg_user_mail = request.args.get('user')
  
    if not arg_role_name or not arg_user_mail:
        flash("no role or user arg")
        return redirect(url_for("recipes.roles"))
        
    role = get_user_datastore().find_role(arg_role_name)
    user = get_user_datastore().get_user(arg_user_mail)

    if not role or not user:
        flash("Invalid role or user")
        return redirect(url_for("recipes.roles"))

    if not user.has_role(role):
        flash("User aleady has not the role")
        return redirect(url_for("recipes.roles"))

    get_user_datastore().remove_role_from_user(user, role.name)
    db.session.commit()
    flash("removed user(%s) from role(%s)" %(user.email, role.name))
    return redirect(url_for("recipes.roles"))

@route_blueprint.route('/rfid-has-role')
def rfid_has_role():
    rfidtag = request.args.get('rfidtag')
    arg_role = request.args.get('role')

    assert rfidtag, "rfidtag arg is empty"
    assert arg_role, "role arg is empty"

    user = get_user_datastore().find_user(rfid_tag=rfidtag)
    role = get_user_datastore().find_role(arg_role)

    assert user, "could not find user"
    assert user.name, "user name is empty"
    assert user.street, "user street is empty"
    assert user.city, "user city is empty"

    assert role, "could not find role"

    assert user.has_role(role.name), "user has not the role"
    
    usage = Usage(type=role.name, duration=1, user_id=current_user.id)
    db.session.add(usage)
    user.usages.append(usage)
    db.session.commit() 

    return jsonify({ "User": user.email }),200

def render_pdf(html):
    from xhtml2pdf import pisa
    from io import BytesIO, StringIO
    pdf = BytesIO()
    pisa.CreatePDF(StringIO(html), pdf)
    resp = pdf.getvalue()
    pdf.close()
    return resp

from flask import make_response

@route_blueprint.route('/invoice')
@login_required
def invoice():
    usage_id = int(request.args.get('usage_id'))

    usage = Usage.query.get(usage_id)

    assert current_user.get_id() != usage.getUser().id

    import datetime
    html = render_template('invoice.html', usage=usage, date=datetime.datetime.now(), user=current_user)
    #return html
    pdf = render_pdf(html)

    response = make_response(pdf)
    response.headers['Content-Type'] = 'application/pdf'

    return response

templates/admin.html
{% extends "base.html" %}

{% block content %}
<a href="{{ url_for('recipes.users') }}">Users</a><br>
<a href="{{ url_for('recipes.roles') }}">Roles</a>
{% endblock %}

templates/base.html
{%  extends "material/base.html" %}

{%  block navbar %}
        <nav class="primary-color" role="navigation">
            <div class="nav-wrapper container">
                <a id="logo-container" class="brand-logo" href="{{ "/" }}">Fablab User Managment</a>

                <ul class="right hide-on-med-and-down">
                    <li {% if request.path == url_for('recipes.home') %}class="active" {% endif %}><a href="{{ url_for('recipes.home')}}">Home</a></li>
                    {% if current_user.is_anonymous %}
                        <li><a href="{{ url_for('security.login')}}">Login</a></li>
                    {% else %}
                        {% if current_user.has_role('admin') %}
                            <li {% if request.path == url_for('recipes.admin') %}class="active" {% endif %}><a href="{{ url_for('recipes.admin')}}">Admin</a></li>
                        {% endif %}

                        <li><a href="{{ url_for('security.logout')}}"><div class="valign-wrapper">{{current_user.email}}<i class="material-icons">logout</i></div></a></li>
                    {% endif %}
                </ul>

                <ul class="right hide-on-med-and-down">
                    <li {% if request.path == url_for('recipes.home') %}class="active" {% endif %}><a href="{{ url_for('recipes.home')}}">Home</a></li>
                    {% if current_user.is_anonymous %}
                        <li><a href="{{ url_for('security.login')}}">Login</a></li>
                    {% else %}
                        {% if current_user.has_role('admin') %}
                            <li {% if request.path == url_for('recipes.admin') %}class="active" {% endif %}><a href="{{ url_for('recipes.admin')}}">Admin</a></li>
                        {% endif %}

                        <li><a href="{{ url_for('security.logout')}}"><div class="valign-wrapper">{{current_user.email}}<i class="material-icons">logout</i></div></a></li>
                    {% endif %}
                </ul>

             </div>
        </nav>
{% endblock %}

templates/confirm.html
{% extends "base.html" %}

{% block content %}
{{ message }}<br><br>
<a href="{{ url_yes }}">Yes</a> <br><br>
<a href="{{ url_no }}">No</a>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<div>Your Acivity</div>
<br>
<table style="width=100%" border="1">
    <tr align="left">
        <th>Date</th>
        <th>Durations in s</th>
        <th>Usage Type</th>
        <th>Invoice</th>
    </tr>
    {% for usage in user.usages %}
    <tr>
        <td>{{ usage.date.strftime("%Y-%m-%d %H:%M:%S") }}</td>
        <td>{{ usage.duration }}</td>
        <td>{{ usage.type }}</td>
        <td><a href="{{ url_for('recipes.invoice', usage_id=usage.id ) }}">invoice</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

templates/invoice.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Rechnung-Id: {{usage.id }}</title>
</head>

<body>
    <table style="width:100%">
        <tr>
           <td>Place for a logo</td> 
           <td>
           <table style="width=100%" align="right">
              <tr>
                  <td align="left">Rechnungsnummer:</td>
                  <td align="right">{{ usage.id }}</td>
              </tr>
              <tr align="right">
                  <td align="left">Datum:</td>
                  <td align="right">{{ date.strftime("%d.%m.%Y")}}</td>
              </tr>
           </table>
           </td>
        </tr>
    </table>
    <table align="left" style="width:100%">
        <tr><td><br><td></tr>
        <tr><td>Kempodium e.V.<td></tr>
        <tr><td>Untere Eicher Straße 3</td></tr>
        <tr><td>87435 Kempten<td></tr>
        <tr><td>info@fablab-allgaeu.de<td></tr>
        <tr><td><br><td></tr>
        
        <tr><td>{{user.name}}</td></tr>
        <tr><td>{{user.street}}</td></tr>
        <tr><td>{{user.city}}</td></tr>
    </table>
    <h2>Rechnung</h2>
    <table style="100%">
        <tr>
            <th align="left">Anzahl</th>
            <th align="left">Einheit</th>
            <th align="left">Einzelpreis</th>
            <th align="left">Beschreibung</th>
            <th align="left">Gesamtpreis</th>
        </tr>
        <tr>
            <td>25</td>
            <td>Minuten</td>
            <td>1€</td>
            <td>Lasercutter</td>
            <td>25€</td>
        </tr>
    </table>
    <br><br>
    <label>Bitte überweisen Sie den Rechnungsbetrag mit der Rechnungsnummer als Verwendungszweck bis zum XXXX auf unser Konto.</label>
    <br><br>
    <table align="left" style="width:100%">
        <tr><td>Kempodium e.V.<td></tr>
        <tr><td>IBAN: ljkadsfalsdkfj</td></tr>
        <tr><td>IBAN: ljkadsfalsdkfj</td></tr>
        <tr><td>Bank: ljkadsfalsdkfj</td></tr>
    </table>
    
</body>
</html>

templates/modify_user.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="post" novalidate>
        {{ form.csrf_token }}
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email(value=user.email, size=32) }}
            <br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.rfid_tag.label }}<br>
            {{ form.rfid_tag(value=user.rfid_tag, size=32) }}
            <br>
            {% for error in form.rfid_tag.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.name.label }}<br>
            {{ form.name(value=user.name, size=32) }}
            <br>
            {% for error in form.name.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.street.label }}<br>
            {{ form.street(value=user.street, size=32) }}
            <br>
            {% for error in form.street.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.city.label }}<br>
            {{ form.city(value=user.city, size=32) }}
            <br>
            {% for error in form.city.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

templates/roles.html
{% extends "base.html" %}

{% block content %}
<h2>Add new role:</h2>
    <form action="" method="post" novalidate>
        {{ form.csrf_token }}
        {{ form.hidden_tag() }}
        <p>
            {{ form.role.label }}<br>
            {{ form.role(size=32) }}
            <br>
            {% for error in form.role.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>

<h2>Roles</h2>
<table style="width=100%" border="1">
    <tr align="left">
        <th>User</th>
        {% for role in Role.query.all() %}
            <th>{{ role.name }}</th>
        {% endfor %}
    </tr>
    {% for user in User.query.all() %}
    <tr>
        <td>{{ user.email }}</td>
        {% for role in Role.query.all() %}
            <td>
                <input type='checkbox'
                {% if user.has_role(role) %}
                    checked 
                    onclick="javascript:window.location.href='{{url_for("recipes.role_rm_user", user=user.email, role=role.name)}}';return false;"
                {% else %}
                    onclick="javascript:window.location.href='{{url_for("recipes.role_add_user", user=user.email, role=role.name)}}';return false;"
                {% endif %}
                >
            </td>
        {% endfor %}
    </tr>
    {% endfor %}
    <tr>
    <td></td>
    {% for role in Role.query.all() %}
        <td><a href="{{ url_for('recipes.role_delete', role=role.name )}}">delete</a></td>
    {% endfor %}
    </tr>
</table>
{% endblock %}

templates/users.html
{% extends "base.html" %}

{% block content %}
<table style="width=100%" border="1">
    <tr align="left">
        <th>email</th>
        <th>rfid tag</th>
<!--        <th>active</th>
        <th>confirmed at</th> -->
        <th>login count</th>
        <th>modify user</th>
    </tr>
    {% for user in users %}
    <tr>
        <td>{{ user.email }}</td>
        <td>{{ user.rfid_tag }}</td>
<!--            <td><input type="checkbox" onclick="return false;"
            {% if user.active is sameas true %}
                checked
            {% endif %}
            ></td>
        <td>{% if user.confirmed_at == 'None' %}
                {{ user.confirmed_at }}
            {% else %}
                not yet
            {% endif %}
        </td> -->
        <td>{{ user.login_count }}</td>
        <td><a href="{{ url_for('recipes.modify_user', email=user.email)}}">modify</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}